# vim: set ft=yaml ts=2 expandtab:
---

- name: converge apparmor
  hosts: localhost
  become: true

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:
  - mafalb.apparmor.apparmor

  tasks:

  - name: mysqld policy is complaining
    mafalb.apparmor.profile:
      name: /usr/sbin/mysqld
      state: complain

...
