# vim: set ft=yaml ts=2 expandtab:
---

- name: apparmor is present
  package:
    name: "{{ packages }}"

- name: apparmor is enabled
  service:
    name: "{{ service }}"
    state: started
  when:
  - not ansible_virtualization_type in ['lxc','docker','containerd','container']

...
