# vim: set ft=yaml ts=2 expandtab:
---

- name: Set up proxy
  hosts: proxy_group

  pre_tasks:

  # https://github.com/geerlingguy/ansible-role-composer/issues/54
  # note that older systemd has no --wait
  # therefore the loop
  #
  - name: Wait for systemd to complete initialization. # noqa 303
    command: systemctl is-system-running --wait
    register: _has_booted
    until: _has_booted.stdout in ['running','degraded']
    retries: 120
    delay: 1
    changed_when: false
    failed_when: false

  roles:

  - name: mafalb.squid.server

...
