# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - c8s
        - debian9
        - debian10
        - ubuntu16
        - ubuntu18
        - ubuntu20
        - ubuntu2104

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

        include:

        - target: c8s
          image: quay.io/centos/centos:stream8

        - target: debian9
          image: docker.io/debian:stretch
        - target: debian10
          image: docker.io/debian:buster
        - target: ubuntu16
          image: docker.io/ubuntu:xenial
        - target: ubuntu18
          image: docker.io/ubuntu:bionic
        - target: ubuntu20
          image: docker.io/ubuntu:focal
        - target: ubuntu2104
          image: docker.io/ubuntu:hirsute

    env:

      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_IMAGE: ${{ matrix.image }}
      CI_HOSTNAME: ci-${{ matrix.target }}
      CI_PRIVILEGED: ${{ matrix.privileged }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/apparmor

    steps:

    - name: checkout collection mafalb.apparmor
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/apparmor

    - name: install molecule
      run: |
        ansible-galaxy collection install mafalb.ansible
        ansible-playbook -e ansible_python_interpreter=python3 -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: molecule default scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

    - name: molecule disable scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test -s disable

    - name: test mafalb.apparmor.policy
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test -s localhost_disable_profile
        molecule test -s localhost_enable_profile

...
